### ISSUE TITLE
Official ouya marketplace still needed?

### ISSUE THREAD

**Issue by cweiske** [ProfessorPopTart/AlternateOuyaStoreProject#1]
I'm not sure if this project is an android app that replaces the ouya in-built store, or if it's an web site / service that implements the same API as ouya.tv so that the official store app on the ouya can access it. Could you please explain?

Also, installation instructions would be nice.

**Comment by ProfessorPopTart** [comment]
Hi, This was an android app that serves as an interface so users that put other roms on the Ouya that didn't have access to Ouyas launcher (like CM10 at the time) could get to the Ouya stores games. So if you run the official Ouya rom then there really is no point to installing this. No work has been done on this in probably 2 years, so I'm not even sure if it works anymore.

More details at the XDA post, http://forum.xda-developers.com/showthread.php?t=2385950

**Comment by cweiske** [comment]
Thanks for the explanation!
